// /src/lib/disposableEmailDomains.ts

/**
 * Lista de dominios de correo temporal y desechable.
 * Bloquea servicios comunes de emails temporales y desechables.
 */
export const DISPOSABLE_EMAIL_DOMAINS = [
  'tempmail.com',
  'mailinator.com',
  '10minutemail.com',
  'yopmail.com',
  'guerrillamail.com',
  'getnada.com',
  'dispostable.com',
  'throwawaymail.com',
  'temp-mail.org',
  'fakeinbox.com',
  'maildrop.cc',
  'jetable.fr',
  'trashmail.com',
  '30minutemail.com',
  '60minutemail.com',
  'mailexpire.com',
  'tempinbox.co',
  'tempmailaddress.com',
  'mailnesia.com',
  'mailsac.com',
  'temp-mail.io',
  'internxt.com',
  'yopmail.com',
  'tempail.com',
  'correotemporal.org',
  'emailondeck.com',
  'yopmail.com',
  'mohmal.com',
  'emailtemporalgratis.com',
  'smailpro.com',
  'tempmail.us.com',
  'sandvpn.com',
  'inboxes.com',
  'tempmailo.com',
  'anonymmail.net',
  'temporarymail.com',
  'tmp.al',
  'mailinator.com',
  'mail.tm',
  'boomlify.com',
] as const;